sudo: false

language: ruby
cache: bundler
rvm:
  - 2.4.6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VER="3.3.0"
    - JEKYLL_VER="3.4.0"
    - JEKYLL_VER="3.5.0"
    - JEKYLL_VER="3.6.0"
    - JEKYLL_VER="3.7.0"
    - JEKYLL_VER="3.8.0"
    - JEKYLL_VER="4.0.0"
    - GH_PAGES=1

dist: trusty

before_install:
  - if [ -z "$JEKYLL_VER" ]; then bundle add github-pages; else bundle add jekyll --version="~>$JEKYLL_VER"; fi;

script:
  - bundle exec jekyll --version
  - bundle exec jekyll build
  - python tests.py

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
